const scheduleData = {
  Monday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "9:20-10:00 AM", activity: "Travel to University" },
    { time: "10:00-1:00 PM", activity: "University Classes" },
    { time: "1:00-1:40 PM", activity: "Travel back home" },
    { time: "1:40-2:00 PM", activity: "Lunch" },
    { time: "2:00-4:00 PM", activity: "AI Project & Python Practice" },
    { time: "4:00-4:15 PM", activity: "Asr Prayer" },
    {
      time: "4:15-5:00 PM",
      activity: "Study or Self-Improvement (Node.js Course)",
    },
    { time: "5:20-5:30 PM", activity: "Maghrib Prayer" },
    { time: "5:30-7:00 PM", activity: "Relax or Family Time" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    { time: "7:15-8:15 PM", activity: "Requirement Engineering Project" },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
    { time: "10:30-11:00 PM", activity: "Wrap Up and Relax" },
  ],
  Tuesday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "9:20-10:00 AM", activity: "Travel to University" },
    { time: "10:30-5:30 PM", activity: "University Classes" },
    { time: "5:30-6:10 PM", activity: "Travel back home" },
    { time: "6:15-6:45 PM", activity: "Dinner" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    {
      time: "7:15-8:15 PM",
      activity: "AI Project Practice (Whisper & Flask)",
    },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
    { time: "10:30-11:00 PM", activity: "Wrap Up and Relax" },
  ],
  Wednesday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "9:20-10:00 AM", activity: "Travel to University" },
    { time: "10:00-2:30 PM", activity: "University Classes" },
    { time: "2:30-3:10 PM", activity: "Travel back home" },
    { time: "3:15-4:00 PM", activity: "Lunch" },
    { time: "4:00-4:15 PM", activity: "Asr Prayer" },
    {
      time: "4:15-5:00 PM",
      activity: "Study Information Security or Python Practice",
    },
    { time: "5:20-5:30 PM", activity: "Maghrib Prayer" },
    { time: "5:30-7:00 PM", activity: "Relax or Family Time" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    { time: "7:15-8:15 PM", activity: "Node.js Course & Logic Building" },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
    { time: "10:30-11:00 PM", activity: "Wrap Up and Relax" },
  ],
  Thursday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "8:00-8:30 AM", activity: "Travel to University" },
    { time: "8:30-5:00 PM", activity: "University Classes" },
    { time: "5:00-5:40 PM", activity: "Travel back home" },
    { time: "5:40-6:15 PM", activity: "Dinner" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    { time: "7:15-8:15 PM", activity: "Research FYP Ideas" },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
    { time: "10:30-11:00 PM", activity: "Wrap Up and Relax" },
  ],
  Friday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "9:20-10:00 AM", activity: "Travel to University" },
    { time: "10:00-3:30 PM", activity: "University Classes" },
    { time: "3:30-4:10 PM", activity: "Travel back home" },
    { time: "4:15-5:00 PM", activity: "Lunch and Relax" },
    { time: "5:20-5:30 PM", activity: "Maghrib Prayer" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    { time: "7:15-8:15 PM", activity: "Portfolio Work (GitHub, etc.)" },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
    { time: "10:30-11:00 PM", activity: "Wrap Up and Relax" },
  ],
  Saturday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "10:00-12:00 PM", activity: "Research for FYP and Requirements" },
    { time: "12:00-1:00 PM", activity: "Lunch" },
    {
      time: "1:00-4:00 PM",
      activity: "Information Security or Scraping Practice",
    },
    { time: "4:00-4:15 PM", activity: "Asr Prayer" },
    { time: "4:15-5:20 PM", activity: "Relax or Family Time" },
    { time: "5:20-5:30 PM", activity: "Maghrib Prayer" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    { time: "7:15-8:15 PM", activity: "Portfolio and Content Creation" },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
  ],
  Sunday: [
    { time: "5:40-6:50 AM", activity: "Fajr Prayer and Quran Recitation" },
    { time: "6:50-7:20 AM", activity: "Workout" },
    { time: "7:20-7:50 AM", activity: "Bath & Freshening Up" },
    { time: "10:00-12:00 PM", activity: "Learning & Exploration (New Tech)" },
    { time: "12:00-1:00 PM", activity: "Lunch" },
    { time: "1:00-4:00 PM", activity: "AI Project and Python Practice" },
    { time: "4:00-4:15 PM", activity: "Asr Prayer" },
    { time: "4:15-5:20 PM", activity: "Relax or Family Time" },
    { time: "5:20-5:30 PM", activity: "Maghrib Prayer" },
    { time: "7:00-7:15 PM", activity: "Isha Prayer" },
    { time: "7:15-8:15 PM", activity: "Self-Improvement Reading or Videos" },
    { time: "8:30-10:30 PM", activity: "Visit Uncle" },
  ],
};



